### ISSUE TITLE
Internal color setting error in simple_crypto

### ISSUE THREAD

**Issue by rbrigden** [openai/multiagent-particle-envs#26]
Hello, I am getting the following error when trying to display a trained policy in simple_crypto

The command I am running:
`$ python experiments/train.py --scenario=simple_crypto --display`

The trace:

Traceback (most recent call last):
  File "experiments/train.py", line 202, in <module>
    train(arglist)
  File "experiments/train.py", line 153, in train
    env.render()
  File "/home/ryan/openai/multiagent-particle-envs/multiagent/environment.py", line 233, in render
    geom.set_color(*entity.color, alpha=0.5)
TypeError: set_color() got multiple values for argument 'alpha'

**Comment by ryan-lowe** [comment]
Hi! Good question --- simple_crypto is not set up to be visualized using `--display`, since the agents don't actually move at all (they simply speak). Instead, if you want to know what the agents are doing, change the `prnt` variable inside `simple_crypto.py`. It should print out the communications of each agent.
