### ISSUE TITLE
Fix:  ImportError: cannot import name 'prng'

### ISSUE THREAD

**Issue by zhaolongkzz** [openai/multiagent-particle-envs#53]
The problem of `prng` is that the gym package is updating, and prng function has been deleted.

you can fix this in code `multiagent-particle-envs/multiagent/multi_discrete.py`

```python
import gym
# from gym.spaces import prng             # this prng has been canceled
```

and change this [line](https://github.com/openai/multiagent-particle-envs/blob/69ee7f85811c77ee651722bc3c332677b2195da1/multiagent/multi_discrete.py#L33) with:
```python
np_random = np.random.RandomState()
random_array = np_random.rand(self.num_discrete_space)
```

**Comment by 0aqz0** [comment]
The version of gym is not correct. You can fix it by
```bash
pip uninstall gym
pip install gym==0.10.5
```

**Comment by zhaolongkzz** [comment]
@0aqz0 yes, the above is what I offer to solve this problem

**Comment by KiyouSen** [comment]
The prng in gym 0.10.x is actually a wrapper of numpy.random. In "prng.py", there is
`np_random = numpy.random.RandomState()`

So instead of downgrade gym, I'd prefer to edit the file "multiagent-particle-envs\multiagent\multi_discrete.py" like this,
`# from gym.spaces import prng  # comment this line

# random_array = prng.np_random.rand(self.num_discrete_space)  # replace this with following one
random_array = np.random.RandomState().rand(self.num_discrete_space)`
